INSERT INTO tipo_login (id, tipo_login) VALUES (1, 'ADMIN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tipo_login (id, tipo_login) VALUES (2, 'CIDADAO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tipo_login (id, tipo_login) VALUES (3, 'FUNCIONARIO') ON CONFLICT (id) DO NOTHING;
INSERT INTO status_cadastro (id, status) VALUES (1, 'PENDENTE') ON CONFLICT (id) DO NOTHING;
INSERT INTO status_cadastro (id, status) VALUES (2, 'CONFIRMADO') ON CONFLICT (id) DO NOTHING;
INSERT INTO login (id, login, password, tipo_login_id) VALUES (1, 'admin', 'admin', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO email_template (id, name, path) VALUES (1, 'default', 'templates/default_email.html') ON CONFLICT (id) DO NOTHING;
INSERT INTO email_template (id, name, path) VALUES (2, 'habilitado', 'templates/habilitado_email.html') ON CONFLICT (id) DO NOTHING;
INSERT INTO horario_vacinacao (id, hora) VALUES (1, '8:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO horario_vacinacao (id, hora) VALUES (2, '8:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO horario_vacinacao (id, hora) VALUES (3, '9:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO horario_vacinacao (id, hora) VALUES (4, '9:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO horario_vacinacao (id, hora) VALUES (5, '10:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO horario_vacinacao (id, hora) VALUES (6, '10:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO horario_vacinacao (id, hora) VALUES (7, '11:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO horario_vacinacao (id, hora) VALUES (8, '11:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO horario_vacinacao (id, hora) VALUES (9, '13:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO horario_vacinacao (id, hora) VALUES (10, '13:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO horario_vacinacao (id, hora) VALUES (11, '14:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO horario_vacinacao (id, hora) VALUES (12, '14:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO horario_vacinacao (id, hora) VALUES (13, '15:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO horario_vacinacao (id, hora) VALUES (14, '15:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO horario_vacinacao (id, hora) VALUES (15, '16:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO horario_vacinacao (id, hora) VALUES (16, '16:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO horario_vacinacao (id, hora) VALUES (17, '17:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO horario_vacinacao (id, hora) VALUES (18, '17:30') ON CONFLICT (id) DO NOTHING;